# api/pdf_utils/resume.py
from __future__ import annotations

from io import BytesIO
from typing import Any, Dict, List, Optional, Tuple

from reportlab.lib.pagesizes import A4, LETTER
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

# Internal imports
from .blocks.base import Frame, RenderContext
from .blocks.registry import get as get_block
from .config import UI_LANG
from .theme_loader import load_and_apply
from .block_aliases import canonicalize
from .engine import LayoutEngine, PageSpec
from .data_utils import _blocks_adapter, build_ready_from_profile as _fallback_build_ready

# ---------------------------------------------------------------------------
# Layout Normalizer
# ---------------------------------------------------------------------------
def _ensure_single_column_layout(layout: dict | None, profile: dict) -> dict:
    """Ensure a valid single-column layout and flow."""
    layout = (layout or {}).copy()
    columns = layout.get("columns") or []
    flow = layout.get("flow") or []

    if not columns:
        columns = [{
            "id": "main",
            "x": 20 * mm,
            "y": 277 * mm,
            "w": 170 * mm,
        }]
        layout["columns"] = columns

    if not flow:
        blocks: list[str] = []
        if profile.get("header") or profile.get("header_name"):
            blocks.append("header_name")
        if profile.get("skills"):
            blocks.append("key_skills")
        if profile.get("projects"):
            blocks.append("projects")
        if profile.get("languages"):
            blocks.append("languages")
        if not blocks:
            blocks = ["header_name"]
        layout["flow"] = [{"column": columns[0]["id"], "blocks": blocks}]
    else:
        for step in layout["flow"]:
            bs = step.get("blocks") or []
            if isinstance(bs, (list, tuple)):
                step["blocks"] = [str(b).strip() for b in bs if str(b).strip()]
            else:
                step["blocks"] = [str(bs).strip()] if str(bs).strip() else []
    return layout

# ---------------------------------------------------------------------------
# Mapper guard & fallback
# ---------------------------------------------------------------------------
try:
    from .data_mapper import map_profile_to_ready  # type: ignore
    _HAS_MAPPER = True
except Exception:  # pragma: no cover
    _HAS_MAPPER = False
    def map_profile_to_ready(
        profile: dict,
        *,
        ui_lang: Optional[str] = None,
        rtl_mode: Optional[bool] = None,
        map_rules_override: Optional[dict] = None,
    ) -> Tuple[Dict[str, Any], List[str]]:
        ready = _fallback_build_ready(profile)
        return ready, []

# ---------------------------------------------------------------------------
# Defaults: page size and margins
# ---------------------------------------------------------------------------
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 18 * mm
RIGHT_MARGIN = 18 * mm
TOP_MARGIN = 22 * mm
BOTTOM_MARGIN = 18 * mm

_PAGE_SIZES = {"A4": A4, "Letter": LETTER}

# ---------------------------------------------------------------------------
# Footer helper (to slightly increase file size & add meta)
# ---------------------------------------------------------------------------
def _add_footer(c: canvas.Canvas, page: Optional[Dict[str, Any]]) -> None:
    try:
        c.setAuthor("Resume Builder Engine")
        c.setTitle("Generated Resume PDF")
    except Exception:
        pass
    # line + tiny text near bottom margin
    footer_y = _get_margin(page, "bottom", default_px=BOTTOM_MARGIN) - 8
    try:
        c.setLineWidth(0.5)
        c.setStrokeGray(0.85)
        c.line(LEFT_MARGIN, footer_y + 6, PAGE_W - RIGHT_MARGIN, footer_y + 6)
    except Exception:
        pass
    try:
        c.setFont("Helvetica", 6)
    except Exception:
        c.setFont("Times-Roman", 6)
    c.setFillGray(0.35)
    c.drawString(LEFT_MARGIN, footer_y, "Generated by API • test build")
    c.setFillGray(0)

# ---------------------------------------------------------------------------
# Public: build
# ---------------------------------------------------------------------------
def build_resume_pdf(
    data: Optional[Dict[str, Any]] = None,
    *,
    layout_plan: Optional[List[Dict[str, Any]]] = None,
    ready: Optional[Dict[str, Any]] = None,
    ui_lang: Optional[str] = None,
    rtl_mode: Optional[bool] = None,
    theme_name: Optional[str] = None,
    theme: Optional[str] = None,
    page: Optional[Dict[str, Any]] = None,
) -> bytes:
    """Build a resume PDF from modern `data` or legacy `layout_plan` + `ready`."""
    if theme and not theme_name:
        theme_name = theme

    # -------- Modern usage (data) --------
    if data is not None:
        ui = data.get("ui_lang") or UI_LANG
        rtl = bool(data.get("rtl_mode"))
        profile = data.get("profile") or {}
        profile = _blocks_adapter(profile)

        # ✅ ensure layout before resolving plan/columns
        data["layout_inline"] = _ensure_single_column_layout(data.get("layout_inline"), profile)

        tn = theme_name or data.get("theme_name") or "default"
        theme_dict = load_and_apply(tn)

        if _HAS_MAPPER:
            li = data.get("layout_inline") or {}
            rd, map_warnings = map_profile_to_ready(
                profile,
                ui_lang=ui,
                rtl_mode=rtl,
                map_rules_override=li.get("map_rules") or {},
            )
            if map_warnings:
                print("[Mapper] warnings:", map_warnings)
        else:
            rd = _fallback_build_ready(profile)

        plan, cols, page_conf = _resolve_layout_columns_page_from_inline(data)
        _apply_page_defaults(page_conf)
        return _render_pdf(
            plan, rd, ui_lang=ui, rtl_mode=rtl, columns=cols, theme=theme_dict, page=page_conf
        )

    # -------- Legacy usage --------
    ui = ui_lang or UI_LANG
    rtl = bool(rtl_mode)
    rd = ready or {}
    plan = layout_plan or _fallback_layout()
    cols = _fallback_columns()
    tn = theme_name or "default"
    theme_dict = load_and_apply(tn)
    page_conf = page or {}
    _apply_page_defaults(page_conf)
    return _render_pdf(
        plan, rd, ui_lang=ui, rtl_mode=rtl, columns=cols, theme=theme_dict, page=page_conf
    )

# ---------------------------------------------------------------------------
# Render
# ---------------------------------------------------------------------------
def _render_pdf(
    layout_plan: List[Dict[str, Any]] | Dict[str, Any],
    ready: Dict[str, Any],
    *,
    ui_lang: str,
    rtl_mode: bool,
    columns: Dict[str, Tuple[float, float]],
    theme: Optional[Dict[str, Any]] = None,
    page: Optional[Dict[str, Any]] = None,
) -> bytes:
    # Modern engine (flow-based)
    if isinstance(layout_plan, dict) and layout_plan.get("flow"):
        pagesize = _resolve_page_size(page)
        buf = BytesIO()
        c = canvas.Canvas(buf, pagesize=pagesize)

        margins = {
            "top":    _get_margin(page, "top",    default_px=TOP_MARGIN),
            "right":  _get_margin(page, "right",  default_px=RIGHT_MARGIN),
            "bottom": _get_margin(page, "bottom", default_px=BOTTOM_MARGIN),
            "left":   _get_margin(page, "left",   default_px=LEFT_MARGIN),
        }
        ps = PageSpec(width=pagesize[0], height=pagesize[1], margins=margins)

        engine = LayoutEngine(
            canvas=c,
            page=ps,
            columns=columns,
            theme=theme or {},
            ui_lang=ui_lang,
            rtl_mode=rtl_mode,
        )
        engine.render_flow(
            flow=layout_plan.get("flow") or [],
            ready=ready,
            overrides=layout_plan.get("overrides") or {},
        )

        # footer here
        _add_footer(c, page)

        c.showPage()
        c.save()
        return buf.getvalue()

    # Legacy block list engine
    if isinstance(layout_plan, dict):
        layout_plan = layout_plan.get("layout", [])

    fixed_plan: List[Dict[str, Any]] = []
    for it in layout_plan or []:
        if isinstance(it, dict) and it.get("block_id"):
            fixed_plan.append(dict(it))
        elif isinstance(it, str) and it.strip():
            fixed_plan.append({"block_id": it.strip()})
        else:
            print(f"[WARN] Skipping invalid layout item in _render: {it!r}")

    for it in fixed_plan:
        it["block_id"] = canonicalize(it["block_id"])

    pagesize = _resolve_page_size(page)
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=pagesize)

    ctx: RenderContext = {
        "ui_lang": ui_lang,
        "rtl_mode": rtl_mode,
        "page_top_y": pagesize[1] - _get_margin(page, "top", default_px=TOP_MARGIN),
        "page_h": pagesize[1],
        "theme": theme or {},
        "columns": columns,
        "page_conf": page or {},
    }

    for block_conf in fixed_plan:
        try:
            raw_id = block_conf.get("block_id")
            if isinstance(raw_id, str) and ":" in raw_id:
                base_id, suffix = (raw_id.split(":", 1) + [None])[:2]
            else:
                base_id, suffix = raw_id, None

            block = get_block(base_id)
            frame_dict = block_conf.get("frame") or {}
            frame = Frame(
                x=float(frame_dict.get("x", _get_margin(page, "left", default_px=LEFT_MARGIN))),
                y=float(frame_dict.get("y", pagesize[1] - _get_margin(page, "top", default_px=TOP_MARGIN))),
                w=float(
                    frame_dict.get(
                        "w",
                        pagesize[0]
                        - _get_margin(page, "left", default_px=LEFT_MARGIN)
                        - _get_margin(page, "right", default_px=RIGHT_MARGIN),
                    )
                ),
            )

            block_data = ready.get(base_id)
            if block_data is None:
                block_data = block_conf.get("data")

            if suffix and isinstance(block_data, dict) and suffix in block_data:
                block_data = block_data[suffix]

            if isinstance(block_data, (list, tuple)):
                block_data = "\n".join(str(x) for x in block_data)

            ctx_local = dict(ctx)
            if suffix:
                ctx_local["section"] = suffix

            new_y = block.render(c, frame, block_data or {}, ctx_local)
            frame.y = new_y

        except Exception as e:  # pragma: no cover
            print(f"[WARN] Block '{block_conf.get('block_id') if isinstance(block_conf, dict) else block_conf}' failed: {e}")
            continue

    # footer here too
    _add_footer(c, page)

    c.showPage()
    c.save()
    return buf.getvalue()

# ---------------------------------------------------------------------------
# Layout/Columns/Page resolution helpers
# ---------------------------------------------------------------------------
def _resolve_layout_columns_page_from_inline(
    data: Dict[str, Any],
) -> Tuple[List[Dict[str, Any]], Dict[str, Tuple[float, float]], Dict[str, Any]]:
    li = data.get("layout_inline") or {}

    # 1) plan
    plan: List[Dict[str, Any]] = []
    flow = li.get("flow") or []
    if flow:
        flat: List[Dict[str, Any]] = []
        for grp in flow:
            for b in grp.get("blocks") or []:
                if isinstance(b, str):
                    flat.append({"block_id": b})
                elif isinstance(b, dict) and b.get("block_id"):
                    flat.append(dict(b))
        plan = flat
    else:
        layout_old = li.get("layout") or []
        for it in layout_old:
            if isinstance(it, str):
                plan.append({"block_id": it})
            elif isinstance(it, dict) and it.get("block_id"):
                plan.append(dict(it))

    # 2) columns
    page_conf = li.get("page") or {}
    cols_def = li.get("columns") or []
    columns: Dict[str, Tuple[float, float]] = {}

    if cols_def:
        # If absolute coordinates provided, use them
        first = cols_def[0]
        if ("x" in first) or ("w" in first):
            try:
                columns = {
                    str(c.get("id") or f"col_{i+1}"): (
                        float(c.get("x", LEFT_MARGIN)),
                        float(c.get("w", (PAGE_W - LEFT_MARGIN - RIGHT_MARGIN))),
                    )
                    for i, c in enumerate(cols_def)
                }
            except Exception:
                # Fallback to percentages if parsing fails
                columns = _columns_from_percentages(cols_def)
        else:
            # Percentage definitions
            columns = _columns_from_percentages(cols_def)
    else:
        # No columns defined -> provide a single 'main' column spanning content width
        total_w = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN
        columns = {"main": (LEFT_MARGIN, total_w)}

    # 3) page
    return plan, columns, page_conf

def _columns_from_percentages(cols_def: List[Dict[str, Any]]) -> Dict[str, Tuple[float, float]]:
    total_w = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN
    x_cursor = LEFT_MARGIN
    out: Dict[str, Tuple[float, float]] = {}
    for c in cols_def:
        cid = str(c.get("id") or "").strip() or f"col_{len(out)+1}"
        w_str = str(c.get("width") or "100%").strip()
        if w_str.endswith("%"):
            try:
                pct = float(w_str[:-1]) / 100.0
            except Exception:
                pct = 1.0
        else:
            pct = 1.0
        w = total_w * pct
        out[cid] = (x_cursor, w)
        gutter_mm = float(c.get("gutter_mm") or 0) * mm
        x_cursor += w + gutter_mm
    return out if out else _fallback_columns()

def _apply_page_defaults(page_conf: Dict[str, Any]) -> None:
    if page_conf is None:
        page_conf = {}
    page_conf.setdefault("size", "A4")
    page_conf.setdefault("orientation", "portrait")
    page_conf.setdefault("margin_mm", {"top": 22, "right": 18, "bottom": 18, "left": 18})
    page_conf.setdefault("gutter_mm", 6)

def _resolve_page_size(page_conf: Optional[Dict[str, Any]]):
    if not page_conf:
        return A4
    size = str(page_conf.get("size") or "A4")
    orient = str(page_conf.get("orientation") or "portrait")
    base = _PAGE_SIZES.get(size, A4)
    if orient == "landscape":
        return base[1], base[0]
    return base

def _get_margin(page_conf: Optional[Dict[str, Any]], side: str, *, default_px: float) -> float:
    if not page_conf:
        return default_px
    m = page_conf.get("margin_mm") or {}
    val = m.get(side)
    try:
        return float(val) * mm if val is not None else default_px
    except Exception:
        return default_px

# ---------------------------------------------------------------------------
# Fallbacks
# ---------------------------------------------------------------------------
def _fallback_layout() -> List[Dict[str, Any]]:
    return [
        {
            "block_id": "header_name",
            "frame": {"x": LEFT_MARGIN, "y": PAGE_H - TOP_MARGIN, "w": PAGE_W - LEFT_MARGIN - RIGHT_MARGIN},
            "data": {"centered": True, "highlight_bg": "#E0F2FE", "box_h_mm": 30},
        },
        {"block_id": "key_skills", "frame": {"x": LEFT_MARGIN, "y": PAGE_H - 60 * mm, "w": 80 * mm}},
        {"block_id": "projects", "frame": {"x": 110 * mm, "y": PAGE_H - 60 * mm, "w": 85 * mm}},
    ]

def _fallback_columns() -> Dict[str, Tuple[float, float]]:
    total_w = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN
    left_w = total_w * 0.4
    right_w = total_w * 0.55
    return {
        "left": (LEFT_MARGIN, left_w),
        "right": (LEFT_MARGIN + left_w + 5 * mm, right_w),
    }
